[package]
name = "admin"
version = "0.1.0"
authors = ["Chris Overcash <covercash2@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
db = { path = "../db" }
clap = "3.0.0-beta.2"
dotenv = "0.15.0"